apiVersion: apps/v1
kind: Deployment
metadata:
  name: datetime-deploy
  labels:
    app: datetime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datetime
  template:
    metadata:
      labels:
        app: datetime
    spec:
      containers:
      - name: app
        image: endeavor6969/go-datetime-app:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
